# Generated by Django 4.0.6 on 2022-07-14 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_services', to='pets.pet')),
                ('pet_services', models.ManyToManyField(related_name='services_list', to='services.service')),
            ],
        ),
    ]
