# Generated by Django 4.0.6 on 2022-07-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='delivered_at',
            field=models.IntegerField(null=True),
        ),
    ]
