# Generated by Django 4.0.6 on 2022-07-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(),
        ),
    ]
